#!/bin/bash -l
#SBATCH --job-name=nx-ic
#SBATCH --output=nx-ic.o%j
#SBATCH --error=nx-ic.e%j
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=23:59:00
#SBATCH --export=NONE

unset SLURM_EXPORT_ENV

module purge
module load mkl/2021.4.0
module load orca/5.0.3
module list

# Newton-X
export NX=/home/woody/bccc/bccc137h/software/newtonx-cs/bin
export PATH=$NX:$PATH

# ORCA wrapper dir (contains 'orca' script)
export ORCA=/home/woody/bccc/bccc137h/orca_nx

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-1}
export MKL_NUM_THREADS=1

echo "Host: $(hostname)"
echo "PWD : $(pwd)"
echo "NX  : $NX"
echo "ORCA (dir for NX): $ORCA"
echo "OMP_NUM_THREADS: $OMP_NUM_THREADS"
ls

# Run Newton-X IC
$NX/moldyn.pl > moldyn.log 2>&1

