from logging import error, warning

from matplotlib.axes import Axes
from matplotlib.figure import Figure, SubFigure
import rdkit.Chem.Draw as rdDraw
import rdkit
import rdkit.Chem as rdChem

import matplotlib as mpl

from .common import centertext
from ...plot.common import figax, mpl_imshow_png


def mol_to_png(mol: rdChem.Mol, width: int = 320, height: int = 240) -> bytes:
    """Helper function to plot an rdkit.Mol object as a 2D structural representation

    Args:
        mol (rdChem.Mol): RDKit representation of the molecule to plot
        width (int, optional): Width of the canvas to plot to. Defaults to 320.
        height (int, optional): Height of the canvas to plot to. Defaults to 240.

    Returns:
        bytes: The drawn structure of the `mol` molecule in 2D as a sequence of bytes.
    """

    d = rdDraw.rdMolDraw2D.MolDraw2DCairo(width, height)

    d.drawOptions().setBackgroundColour((1, 1, 1, 0))
    d.drawOptions().padding = 0.05

    d.DrawMolecule(mol)
    d.FinishDrawing()
    return d.GetDrawingText()


def format_inchi(inchi: str) -> str:
    """Helper function to split an inchi string across
    multiple lines to not overlap other plots in the DataSheet pages.

    Args:
        inchi (str): InChi string as generated by RDKit

    Returns:
        str: The string broken into multiple lines with inserted \\n characters.
    """
    if len(inchi) < 30:
        return inchi
    else:
        split = inchi.split('/')
        if len(split) not in {4, 5}:
            warning(f"Unexpected InChi: {split=}")
        lens = [len(s) for s in split]
        split[2] = '\n' + split[2]
        if sum(lens[2:]) > 30:
            split[3] = '\n' + split[3]
        return '/'.join(split)


def plot_structure(
    mol: rdChem.Mol,
    name: str = '',
    smiles: str | None = None,
    inchi: str | None = None,
    fig: Figure | SubFigure | None = None,
    ax: Axes | None = None,
) -> Axes:
    """Plot function to create a 2d structure representation of a molecule `mol` using rdkit and create a graph with
    a 2d image representation into `fig` or `ax` with at least one of the two needing to be provided.

    Args:
        mol (rdChem.Mol): The RDKit molecule object to visualize.
        name (str, optional): The name of the structure. Would be used as a plot title if not empty. Defaults to ''.
        smiles (str | None, optional): Smiles strings to include in the x-axis label. Defaults to None.
        inchi (str | None, optional): InChI strings to include in the x-axis label. Defaults to None.
        fig (Figure | SubFigure | None, optional): Figure to plot the graphic into if `ax` not provided. Defaults to None.
        ax (Axes | None, optional): Axis to plot the graphic into. Defaults to None, meaning they will be created from `fig`.

    Returns:
        Axes: The axes the graphic was plotted to.
    """
    fig, ax = figax(fig, ax)
    try:
        png = mol_to_png(mol)
    except ImportError as err:
        error(
            "ImportError from rdkit.Chem.Draw while "
            f"attempting to plot structure: {err}"
        )
        centertext("ImportError while attempting\nto plot structure", ax)
        return ax

    mpl_imshow_png(ax, png)

    if len(name) > 0:
        ax.set_title(name)

    ax.axis('on')
    ax.get_yaxis().set_visible(False)
    ax.tick_params(axis="x", bottom=False, labelbottom=False)
    xlabel_string = ""
    # Add smiles to label if provided
    if smiles is not None:
        xlabel_string = f"SMILES={smiles}"

    # Add InChI to label if provided
    if inchi is not None:
        inchi = format_inchi(inchi)
        if len(xlabel_string) > 0:
            xlabel_string += '\n'
        xlabel_string += f"{inchi}"

    ax.set_xlabel(xlabel_string, fontsize='small')
    # axy.tick_params(axis="y", labelleft=False)
    return ax
